name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["**"]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: python/.python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv sync --locked --dev
      - run: uv run mypy .

      - run: uv run ruff check --output-format=github
        id: ruff-check
      - run: uv run ruff format --check --output-format=github
        # run format even if ruff check failed
        if: success() || steps.ruff-check.conclusion == 'failure'

  python-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: python/.python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv sync --locked --dev
      - run: uv run pytest -v
      - run: uv build --verbose

  python-publish-testpypi:
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
    needs: [python-lint, python-test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: python/.python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv build --verbose

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          attestations: false # https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440

  python-publish-pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]'
    needs: [python-lint, python-test, python-publish-testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/hue-zigbee-encoding/
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: python/.python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv build --verbose

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
