name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv sync --locked --dev
      - run: uv run pytest -v
      - run: uv run mypy .
      - run: uv run ruff check
      - run: uv build
      - run: uv publish --dry-run --trusted-publishing never

  publish-testpypi:
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/hue-zigbee-encoding/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv build
      - run: uv publish --check-url https://test.pypi.org/simple/ --publish-url https://test.pypi.org/legacy/

  publish-pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [test, publish-testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/hue-zigbee-encoding/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - uses: astral-sh/setup-uv@v6

      - run: uv build
      - run: uv publish
